import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pixelCraft = localFont({
  src: "../../public/fonts/Pixel-Craft.ttf",
  variable: "--font-pixel-craft",
});

const retron2000 = localFont({
  src: "../../public/fonts/Retron2000.ttf",
  variable: "--font-retron2000",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${pixelCraft.variable} ${retron2000.variable} font-sans`}
    >
      <body className={`bg-ctp-crust`}>{children}</body>
    </html>
  );
}
